"""add_stripe_payment_fields

Revision ID: ae790370792b
Revises: 27e17711c1a2
Create Date: 2026-04-13 21:48:40.520849

"""
from typing import Sequence, Union

import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae790370792b'
down_revision: Union[str, None] = '27e17711c1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('payment_token', sa.String(length=36), nullable=True))
    op.add_column('invoices', sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_invoices_payment_token'), 'invoices', ['payment_token'], unique=True)
    # ### end Alembic commands ###

    # Backfill existing invoices with payment tokens
    invoices = sa.table('invoices', sa.column('id', sa.Integer), sa.column('payment_token', sa.String))
    conn = op.get_bind()
    rows = conn.execute(sa.select(invoices.c.id).where(invoices.c.payment_token.is_(None))).fetchall()
    for row in rows:
        conn.execute(
            invoices.update().where(invoices.c.id == row[0]).values(payment_token=str(uuid.uuid4()))
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_payment_token'), table_name='invoices')
    op.drop_column('invoices', 'stripe_checkout_session_id')
    op.drop_column('invoices', 'payment_token')
    # ### end Alembic commands ###
